# generated by Neptune Namespaces v1.x.x
# file: tests/Art/Ery/Pusher/namespace.coffee

Ery = require '../namespace'
module.exports = Ery.Pusher ||
Ery.addNamespace 'Pusher', class Pusher extends Neptune.Base
  ;