# generated by Neptune Namespaces v3.x.x
# file: tests/Art.Ery.Pusher/namespace.coffee

module.exports = (require '../namespace').addNamespace('Art.Ery.Pusher', class Pusher extends Neptune.PackageNamespace)
