# generated by Neptune Namespaces v1.x.x
# file: tests/Art/Ery/Pusher/Pipelines/namespace.coffee

Pusher = require '../namespace'
module.exports = Pusher.Pipelines ||
Pusher.addNamespace 'Pipelines', class Pipelines extends Neptune.Base
  ;