# generated by Neptune Namespaces v3.x.x
# file: tests/Art.EryExtensions.Pusher/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  PusherFilter:         require './PusherFilter'        
  PusherFluxModelMixin: require './PusherFluxModelMixin'
require './Pipelines'