# generated by Neptune Namespaces v3.x.x
# file: tests/Art.EryExtensions.Pusher/namespace.coffee

module.exports = (require '../namespace').addNamespace('Art.EryExtensions.Pusher', class Pusher extends Neptune.PackageNamespace)
require './Pipelines/namespace'