# generated by Neptune Namespaces v3.x.x
# file: tests/Art.EryExtensions.Pusher/Pipelines/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  SimpleStore: require './SimpleStore'