# generated by Neptune Namespaces v3.x.x
# file: tests/Art.EryExtensions.Pusher/Pipelines/namespace.coffee

module.exports = (require '../namespace').addNamespace('Pipelines', class Pipelines extends Neptune.PackageNamespace)
