# generated by Neptune Namespaces v3.x.x
# file: Art.EryExtensions.Pusher/namespace.coffee

module.exports = (require 'neptune-namespaces').addNamespace 'Art.EryExtensions.Pusher', class Pusher extends Neptune.PackageNamespace
  @version: require('../../package.json').version
